### ISSUE TITLE
Add cscore/cameraserver integration back in

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#616]
Should just be copy/paste from the old repo. Need to build/install cscore for roborio too.

**Comment by ArchdukeTim** [comment]
Can this not be autogenerated?

**Comment by auscompgeek** [comment]
No, we want to keep our cscore out of main process. Also we don't want cscore to be a dependency here otherwise packaging will be impossible.

**Comment by amoose136** [comment]
Without  some way to get CSCore I can't run the example multiCameraServer.py that comes with wpilibsuite/FRCVision-pi-gen locally on a windows installation.

**Comment by virtuald** [comment]
@amoose136 running cscore locally is actually an annoying proposition, see https://github.com/robotpy/robotpy-cscore/issues/17 ... though, if we packaged OpenCV with robotpy-build, I wonder if we could pull it off?

**Comment by amoose136** [comment]
I may have to try the conda thing. I don't really like conda as I don't think it solves the problems it's designed to solved so I'd rather just use stock python.  I was able to get opencv to compile using visual studio community edition but that didn't fix the missing header error when building CSCore and the wheel file linked doesn't actually work anymore either because the version of opencv I built was 4.x series not 3.x series.
