### ISSUE TITLE
Use enum.Enum instead of integer constants?

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-wpilib#78]
Most of the objects we use have a number of integer constants that are really enums. Python 3.4 has support for enums, so should we use it?

If we don't do it now, then changing it later will be a backwards compatibility problem.

**Comment by virtuald** [comment]
Going to put this off until next year.

**Comment by auscompgeek** [comment]
Consensus seems to be to use `enum.IntEnum` where appropriate now, especially cases where we need to look up names from values.

We should explicitly deprecate the use of plain integers though, and probably change them to use `enum.Enum` after a year or two.

I'd love to see `enum.IntFlag` used here too, but it's new in Python 3.6, so that's going to be a showstopper for it for a couple of years…

**Comment by virtuald** [comment]
Now that the type hints are in, this would be a good thing to do... @ArchdukeTim had a branch that did this?

**Comment by ArchdukeTim** [comment]
I think so? Lemme check. I probably didn't get too far

**Comment by ArchdukeTim** [comment]
Especially when dealing with hal, `enum.Enum` won't work due to checks for instances of `int`. There are other places (driverstation.py is one example) where `<=` is done to the enum, so `IntEnum` is required there, and some of the tests use aliases for the enums, and `==` doesn't work based on value. So we should use `IntEnum` for now, and maybe do some cleanup to get `Enum` to work

**Comment by auscompgeek** [comment]
> Especially when dealing with hal, enum.Enum won't work due to checks for instances of int.

I don't see how this would be a problem. Enum variants have values.

> There are other places (driverstation.py is one example) where <= is done to the enum

Then we compare its value instead, or implement the ordering protocol on the enum.

> some of the tests use aliases for the enums, and == doesn't work based on value

I don't see how this would be an issue?

> So we should use IntEnum for now

We have backwards-compatibility concerns here, so we should change the existing "enums" to IntEnums first anyway.

**Comment by ArchdukeTim** [comment]
@auscompgeek we could change stuff, but I don't wanna go through all the tests and update them to work with `Enum`. But for now, using `Enum` in certain places breaks

**Comment by auscompgeek** [comment]
Looks like everything's an IntEnum now at least (except for RobotDrive.MotorType).

**Comment by virtuald** [comment]
OBE
